### ISSUE TITLE
[SEC-F19] Upgrades fail if storage is too big

### ISSUE THREAD

**Issue by krpeacock** [dfinity/invoice-canister#23]
## Observation
Upgrades work by serializing the invoices to stable memory. 

## Risk Description
If the invoices HashMap reaches a certain size, the pre_upgrade hook will no longer be able to serialize the invoices because it has a limit in how much computation it can do. This will render the canister impossible to upgrade. 

## Recommendations
* Consider writing the invoices to stable memory directly to avoid this problem. 
* See best practices [here](https://github.com/85d0acbc9e314a199c86d799dc6fad44#874bad246c184e0193a93cb811a482e4).

**Comment by icnaming-roy** [comment]
What about make "best practices" public, I can not access it now.

**Comment by krpeacock** [comment]
I actually can't access it either 😅
